# Generated by Django 4.1 on 2022-09-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("postings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="operatingcomment",
            name="operating_board_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postings.operatingboardposting",
            ),
        ),
        migrations.AddField(
            model_name="operatingcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="operatingboardposting",
            name="comment",
            field=models.ManyToManyField(
                related_name="operatin_comment",
                through="postings.OperatingComment",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="operatingboardposting",
            name="view",
            field=models.ManyToManyField(
                related_name="operating_view",
                through="postings.OperatingView",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="noticeview",
            name="notice_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postings.noticeboardposting",
            ),
        ),
        migrations.AddField(
            model_name="noticeview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="noticecomment",
            name="notice_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postings.noticeboardposting",
            ),
        ),
        migrations.AddField(
            model_name="noticecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="noticeboardposting",
            name="comment",
            field=models.ManyToManyField(
                related_name="notice_comment",
                through="postings.NoticeComment",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="noticeboardposting",
            name="view",
            field=models.ManyToManyField(
                related_name="notice_view",
                through="postings.NoticeView",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="freeview",
            name="free_board_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postings.freeboardposting",
            ),
        ),
        migrations.AddField(
            model_name="freeview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="freecomment",
            name="free_board_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="postings.freeboardposting",
            ),
        ),
        migrations.AddField(
            model_name="freecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="freeboardposting",
            name="comment",
            field=models.ManyToManyField(
                related_name="posting_comment",
                through="postings.FreeComment",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="freeboardposting",
            name="view",
            field=models.ManyToManyField(
                related_name="posting_view",
                through="postings.FreeView",
                to="users.user",
            ),
        ),
    ]
