# Generated by Django 4.1 on 2022-09-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_free_board_remove_user_notice_and_more"),
        ("postings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeboardposting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="noticeboardposting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="operatingboardposting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
