# Generated by Django 4.1 on 2022-09-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=100)),
                ("psword", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("level", models.CharField(default=1, max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "free_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postings.freeboardposting",
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postings.noticeboardposting",
                    ),
                ),
                (
                    "operation_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postings.operatingboardposting",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Updated_time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "update_time",
            },
        ),
    ]
