# Generated by Django 4.1 on 2022-09-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_free_board_alter_user_notice_and_more"),
        ("users", "0002_remove_user_free_board_remove_user_notice_and_more"),
    ]

    operations = []
