# Generated by Django 4.1 on 2022-09-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20220903_1553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="free_board",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notice",
        ),
        migrations.RemoveField(
            model_name="user",
            name="operation_board",
        ),
    ]
